### PR TITLE
[Fix] Automatically assign `IS_OWNER` permission to sql warehouse if not specified

### LINKED ISSUE #3730: [ISSUE] `databricks_permissions` shows permanent drift if the owner is not the same as the TF identifier
### Configuration

```hcl
resource "databricks_permissions" "sql_warehouse" {
    access_control {
        group_name = "users"
        permission_level = "CAN_MONITOR"
    }
    sql_endpoint_id = "fba2ef8e11b2c0a3" # this endpoint is owned by a different principal
}
```

### Expected Behavior

tf plan should be clean

### Actual Behavior

tf plan shows planned changes
```
  ~ resource "databricks_permissions" "sql_warehouse" {
        id              = "/sql/warehouses/xxx"
        # (2 unchanged attributes hidden)

      - access_control {
          - permission_level       = "IS_OWNER" -> null
          - user_name              = "xxx.xxx@databricks.com" -> null
            # (2 unchanged attributes hidden)
        }
      - access_control {
          - group_name             = "users" -> null
          - permission_level       = "CAN_MONITOR" -> null
            # (2 unchanged attributes hidden)
        }
      + access_control {
          + group_name       = "users"
          + permission_level = "CAN_MONITOR"
        }
    }
```

### Terraform and provider versions
1.48.2

### Important Factoids
Running terraform apply does not clear the diff

### PR DESCRIPTION
**Pull request by nkvuong**
## Changes
- SQL warehouses supports specifying `IS_OWNER` permission and therefore requires the same workaround as jobs & pipelines.
- Resolves #3730

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [x] covered with integration tests in `internal/acceptance`
- [x] relevant acceptance tests are passing
- [x] using Go SDK

### CODE REVIEW

File: permissions/resource_permissions.go [hunk 1]
```diff
@@ -133,6 +133,44 @@ func (a PermissionsAPI) shouldExplicitlyGrantCallingUserManagePermissions(object
...
+				return "", nil
+			}
+			return "", err
+		}
+		return job.CreatorUserName, nil
+	} else if strings.HasPrefix(objectID, "/pipelines") {
+		pipeline, err := w.Pipelines.GetByPipelineId(a.context, strings.ReplaceAll(objectID, "/pipelines/", ""))
+		if err != nil {
+			return "", err
+		}
```
Comment (alexott) [inline permissions/resource_permissions.go:162]: Should we handle the "doesn't exist" case for the rest of objects?

**Review by alexott — APPROVED** [review]
codewise is good, just one comment

File: permissions/resource_permissions.go (hunk 1 above)
Comment (nkvuong) [reply permissions/resource_permissions.go]: added the error suppression

**Comment by nkvuong** [comment]
actually, this previously has caused regression - #2678

basically for sql warehouses with no existing owner, this would fail - so we need some automatic retry in this case

**Comment by nkvuong** [comment]
Integration tests passed - failed tests are unrelated

**Review by tanmay-db — APPROVED** [review]

**Comment by shortpoet** [comment]
Thank you all very much for this fix! 🥇
