### PR TITLE
Export predefined `databricks_cluster_policy` as data sources

### LINKED ISSUE #1785: [ISSUE] Issue with `databricks_cluster_policy` resource. Data block needed
When a user authors a terraform descriptor file (.tf file) to create a policy with one of these names:

1. Personal Compute
2. Power User Compute
3. Shared Compute
4. Job Compute

Errors are thrown

### Expected Behavior
For terraform resource like

```
resource "databricks_cluster_policy" {
  name = "Job Compute"
  definition =.....
}
```

The policy should either be created or ignored.

### Actual Behavior
The back end of the API throws an error informing the user that, "This policy already exists"

### Steps to Reproduce
Attempt to create a databricks cluster policy named Job Compute (or one of those listed above) using Terraform

### Exporter Notes
This isn't an exporter related ticket but the exporter will fetch all policies and an attempt to re-create them in a target workspace will fail.

These policies should be handled in a special way - ie. by using a a data block - and this ticket is about implementing that block.

### PR DESCRIPTION
**Pull request by alexott**
Also, emit init scripts defined in the cluster policies

This fixes #1785

### CODE REVIEW

File: exporter/importables.go [hunk 1]
```diff
@@ -454,11 +457,13 @@ var resourcesMap map[string]importable = map[string]importable{
...
-			ic.Emit(&resource{
-				Resource: "databricks_permissions",
-				ID:       fmt.Sprintf("/cluster-policies/%s", r.ID),
-				Name:     "clust_policy_" + ic.Importables["databricks_cluster_policy"].Name(r.Data),
-			})
+			if ic.meAdmin {
+				ic.Emit(&resource{
+					Resource: "databricks_permissions",
+					ID:       fmt.Sprintf("/cluster-policies/%s", r.ID),
+					Name:     "clust_policy_" + ic.Importables["databricks_cluster_policy"].Name(r.Data),
```
Comment (nfx) [inline exporter/importables.go:464]:
```suggestion
					Name:     "cluster_policy_" + ic.Importables["databricks_cluster_policy"].Name(r.Data),
```

File: exporter/importables.go [hunk 2]
```diff
@@ -467,26 +472,37 @@ var resourcesMap map[string]importable = map[string]importable{
 			for k, policy := range definition {
 				value, vok := policy["value"]
 				defaultValue, dok := policy["defaultValue"]
-				if !vok && !dok {
+				typ, tok := policy["type"]
+				if !vok && !dok && !tok {
 					continue
```
Comment (nfx) [inline exporter/importables.go:477]: please add a log line why something is skipped here

File: exporter/importables.go [hunk 3]
```diff
@@ -467,26 +472,37 @@ var resourcesMap map[string]importable = map[string]importable{
...
 				}
+				stringValue := eitherString(value, defaultValue)
```
Comment (nfx) [inline exporter/importables.go:479]: don't add variable refactors if they're not needed

File: exporter/importables.go [hunk 4]
```diff
@@ -467,26 +472,37 @@ var resourcesMap map[string]importable = map[string]importable{
...
 				}
-				if k == "instance_pool_id" {
+				if k == "instance_pool_id" || k == "driver_instance_pool_id" {
 					ic.Emit(&resource{
 						Resource: "databricks_instance_pool",
-						ID:       eitherString(value, defaultValue),
+						ID:       stringValue,
 					})
 				}
+				if typ == "fixed" && strings.HasPrefix(k, "init_scripts.") && strings.HasSuffix(k, ".dbfs.destination") {
```
Comment (nfx) [inline exporter/importables.go:492]: nit: could you split to multiple lines

File: exporter/importables.go [hunk 5]
```diff
@@ -467,26 +472,37 @@ var resourcesMap map[string]importable = map[string]importable{
...
+					ic.emitIfDbfsFile(stringValue)
+				}
+			}
+			policyName := r.Data.Get("name").(string)
+			if slices.Contains(predefinedClusterPolicies, policyName) {
+				r.Mode = "data"
+				r.Data.Set("definition", "")
```
Comment (nfx) [inline exporter/importables.go:499]: add comment explaining why this is happening

**Review by nfx — COMMENTED** [review]
please address the comments. mainly adding more comments.

**Review by nfx — APPROVED** [review]
