### PR TITLE
Fix missing attributes from `databricks_job` data source

### LINKED ISSUE #1797: [ISSUE] Issue with databricks_job Data Source
### Configuration
```hcl
terraform {
    required_providers {
      databricks = {
        source = "databricks/databricks"
        version = "1.6.5"
      }
    }
}

data "databricks_jobs" "this" {
  job_name = "Vivian-auto-test"
}

output "raw_out" {
  value     = data.databricks_job.this
}
```

### Expected Behavior

The output has to fetch all the job configurations. The field under "job_settings" is not getting populated.
### Actual Behavior

The output of databricks_job does not populate data in the "job_settings" list in its output JSON.
### Steps to Reproduce

You can easily reproduce this using the above hcl code that I have attached.
### Terraform and provider versions

Terraform v1.3.5
on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.6.5
### Debug Output

Debug logs: https://gist.github.com/vivianwilfred/bbbdfd4277fde352dbc3d3a4f0ecc467

### PR DESCRIPTION
**Pull request by nkvuong**
This happens because we did not set expandTasks to the API when listing the jobs. For search by id, list without expandTasks and then re-search when job name is found 

This closes #1797

### CODE REVIEW

File: jobs/data_job.go [hunk 1]
```diff
@@ -20,9 +20,29 @@ func DataSourceJob() *schema.Resource {
 		var list []Job
 		var err error
 		if data.Name != "" {
-			list, err = jobsAPI.ListByName(data.Name, false)
+			list, err = jobsAPI.ListByName(data.Name, true)
 		} else {
+			// if name is not provided, need to list all the jobs and search by id
+			// does not expand tasks to limit the results size
 			list, err = jobsAPI.List()
```
Comment (alexott) [inline jobs/data_job.go:27]: If we have a job ID, then why not simply call `Read` using that ID? It will be more efficient :-)

**Review by alexott — CHANGES_REQUESTED** [review]

File: jobs/data_job.go (hunk 1 above)
Comment (nkvuong) [reply jobs/data_job.go]: this is a lot simpler now

**Review by alexott — APPROVED** [review]
lgtm. Thank you for simplifying it
