### PR TITLE
Automatically add `CAN_MANAGE` permission on `databricks_sql_endpoint` for calling user

### LINKED ISSUE #2165: [ISSUE] Issue with `databricks_permissions` resource on `databricks_sql_endpoint`
Setting `databricks_permissions` on `sql_endpoint_id` removes the CAN_MANAGE permissions from the creator of the SQL warehouse(endpoint)

### Configuration
```hcl
resource "databricks_sql_endpoint" "this" {
  name             = "test"
  cluster_size     = "Small"
  max_num_clusters = 1

}

resource "databricks_permissions" "endpoint_usage" {
  sql_endpoint_id = databricks_sql_endpoint.this.id

  access_control {
    group_name       = "Automation"
    permission_level = "CAN_MANAGE"
  }

  access_control {
    group_name       = "Engineering"
    permission_level = "CAN_USE"
  }
}
```

### Expected Behavior
Expecting the groups Automation to have CAN_MANAGE, Engineering to have CAN_USE, Admins to have CAN_MANAGE and the creator to have CAN_MANAGE

### Actual Behavior
Automation has CAN_MANAGE, Engineering has CAN_USE, Admins has CAN_MANAGE but the creator has no permissions. 

### Steps to Reproduce
terraform apply

### Terraform and provider versions
Terraform v1.3.9
on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.11.1

### PR DESCRIPTION
**Pull request by nkvuong**
## Changes
- Automatically add `CAN_MANAGE` permission for calling user to `databricks_sql_endpoint` closes #2165
- Refactor some API calls in `databricks_permissions` to use Go SDK

## Tests

- [ ] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

### CODE REVIEW

**Comment by mkazia-db** [comment]
Why is this handled different from clusters? Why not add `"/sql/warehouses/"` in function `shouldExplicitlyGrantCallingUserManagePermissions`

File: permissions/resource_permissions.go [hunk 1]
```diff
@@ -176,6 +174,21 @@ func (a PermissionsAPI) Update(objectID string, objectACL AccessControlChangeLis
 			PermissionLevel: "CAN_MANAGE",
 		})
 	}
+	w, err := a.client.WorkspaceClient()
+	if err != nil {
+		return err
+	}
+	if strings.HasPrefix(objectID, "/sql/warehouses") {
+		warehouse, err := w.Warehouses.GetById(a.context, strings.ReplaceAll(objectID, "/sql/warehouses/", ""))
```
Comment (nfx) [inline permissions/resource_permissions.go:182]: for debuggability, could you extract `strings.ReplaceAll(objectID, "/sql/warehouses/", "")` to a variable?

File: permissions/resource_permissions.go [hunk 2]
```diff
@@ -176,6 +174,21 @@ func (a PermissionsAPI) Update(objectID string, objectACL AccessControlChangeLis
...
+		if err != nil {
+			return err
+		}
+		// add CAN_MANAGE permission for creator
+		objectACL.AccessControlList = append(objectACL.AccessControlList, AccessControlChange{
+			UserName:        warehouse.CreatorName,
```
Comment (nfx) [inline permissions/resource_permissions.go:188]: will it work if it's a service principal? check `azure-prod` env

File: permissions/resource_permissions.go [hunk 3]
```diff
@@ -213,8 +226,16 @@ func (a PermissionsAPI) Delete(objectID string) error {
 			}
 		}
 	}
+	w, err := a.client.WorkspaceClient()
+	if err != nil {
+		return err
+	}
 	if strings.HasPrefix(objectID, "/jobs") {
-		job, err := jobs.NewJobsAPI(a.context, a.client).Read(strings.ReplaceAll(objectID, "/jobs/", ""))
+		job_id, err := strconv.ParseInt(strings.ReplaceAll(objectID, "/jobs/", ""), 10, 0)
```
Comment (nfx) [inline permissions/resource_permissions.go:234]: rename `job_id` to `jobID` - golang naming conventions for hand-written code🤷

**Review by nfx — CHANGES_REQUESTED** [review]

File: permissions/resource_permissions.go (hunk 3 above)
Comment (nkvuong) [reply permissions/resource_permissions.go]: fixed

**Comment by nkvuong** [comment]
@mkazia-db Adding warehouse `shouldExplicitlyGrantCallingUserManagePermissions` will fix this issue (calling user permission is removed), but not the edge case where the creator is not the same as the calling user

@nfx when I tested this further, automatically adding permission to the warehouse creator results in permanent diff (as the extra permission is returned in the API). For now I'll apply the quick fix, and handle that extra edge case properly

File: permissions/resource_permissions.go (hunk 2 above)
Comment (nkvuong) [reply permissions/resource_permissions.go]: our API accepts service principal as UserName fine...which is the cause of #2131

**Comment by nkvuong** [comment]
acceptance tests passed

**Review by nfx — APPROVED** [review]
