### PR TITLE
`databricks_job`: `instance_pool_id` takes precedence over `node_type_id` in `Update`

### LINKED ISSUE #2141: [ISSUE] Can't update existing `databricks_job` to use instance pool when `node_type_id` was configured before
Existing `databricks_job` can't be updated to use instance pool if it was configured with explicit `node_type_id`

### Expected Behavior

Job needs to be updated to use instance pools 

### Actual Behavior

```
  # databricks_job.this will be updated in-place
  ~ resource "databricks_job" "this" {
        id                        = "212137686109752"
        name                      = "My job"
        # (8 unchanged attributes hidden)
      ~ task {
            # (5 unchanged attributes hidden)
          ~ new_cluster {
              + instance_pool_id             = "0322-114546-stern33-pool-7izzz25u"
                # (12 unchanged attributes hidden)
                # (1 unchanged block hidden)
            }
            # (2 unchanged blocks hidden)
        }
        # (3 unchanged blocks hidden)
    }

│ Error: cannot update job: The field 'node_type_id' cannot be supplied when an instance pool ID is provided.
│
│   with databricks_job.this,
│   on main.tf line 23, in resource "databricks_job" "this":
│   23: resource "databricks_job" "this" {
```

### Steps to Reproduce

1. Create a job that explicitly specifies node type ID
2. Update job to use instance pool
3. apply fails

### Terraform and provider versions

master as of 22.03.2023

### LINKED ISSUE #2502: [ISSUE] `databricks_job`: cannot update `new_cluster` from `node_type_id` to `instance_pool_id`
### Configuration
See reproducing test case: https://github.com/marekbrysa/terraform-provider-databricks/commit/b30d11538196ffa2d0c62d8a9d538f7c5b73436a

### Expected Behavior
Existing job with `new_cluster` can be updated to switch from using `node_type_id` to `instance_pool_id`.
Only `instance_pool_id` is present in the request sent to the API.

### Actual Behavior
Applying fails with `Error: cannot update job: The field 'node_type_id' cannot be supplied when an instance pool ID is provided.`
In the request sent to API, both `node_type_id` and `instance_pool_id` are sent, even thought only `instance_pool_id` is present in new HCL.

### Steps to Reproduce
See reproducing test case: https://github.com/marekbrysa/terraform-provider-databricks/commit/b30d11538196ffa2d0c62d8a9d538f7c5b73436a

The test fails with:
```
Error:      	Not equal:
        	            	expected: map[string]interface {}{"job_id":789, "new_settings":map[string]interface {}{"max_concurrent_runs":1, "max_retries":3, "min_retry_interval_millis":5000, "name":"Featurizer New", "new_cluster":map[string]interface {}{"driver_instance_pool_id":"instance-pool-driver", "instance_pool_id":"instance-pool-worker", "num_workers":1, "spark_version":"spark-1"}, "retry_on_timeout":true}}
        	            	actual  : map[string]interface {}{"job_id":789, "new_settings":map[string]interface {}{"max_concurrent_runs":1, "max_retries":3, "min_retry_interval_millis":5000, "name":"Featurizer New", "new_cluster":map[string]interface {}{"driver_instance_pool_id":"instance-pool-driver", "driver_node_type_id":"driver-node-type-id", "instance_pool_id":"instance-pool-worker", "node_type_id":"node-type-id", "num_workers":1, "spark_version":"spark-1"}, "retry_on_timeout":true}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -7,5 +7,7 @@
        	            	   (string) (len=4) "name": (string) (len=14) "Featurizer New",
        	            	-  (string) (len=11) "new_cluster": (map[string]interface {}) (len=4) {
        	            	+  (string) (len=11) "new_cluster": (map[string]interface {}) (len=6) {
        	            	    (string) (len=23) "driver_instance_pool_id": (string) (len=20) "instance-pool-driver",
        	            	+   (string) (len=19) "driver_node_type_id": (string) (len=19) "driver-node-type-id",
        	            	    (string) (len=16) "instance_pool_id": (string) (len=20) "instance-pool-worker",
        	            	+   (string) (len=12) "node_type_id": (string) (len=12) "node-type-id",
        	            	    (string) (len=11) "num_workers": (float64) 1,
        	Test:       	TestResourceJobUpdate_NodeTypeToInstancePool
        	Messages:   	json strings do not match
```

### Terraform and provider versions
master

### PR DESCRIPTION
**Pull request by marekbrysa**
## Changes
`NodeTypeID` cannot be set in `jobsAPI.Update()` if `InstancePoolID` is specified.
If both are specified, assume `InstancePoolID` takes precedence and `NodeTypeID` is only computed.

Closes #2502.
Closes #2141.

## Tests
- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [ ] using Go SDK

### CODE REVIEW

File: jobs/resource_job.go [hunk 1]
```diff
@@ -823,6 +823,15 @@ func ResourceJob() *schema.Resource {
...
 			}
+			// NodeTypeID cannot be set in jobsAPI.Update if InstancePoolID is specified.
+			// If both are specified, assume InstancePoolID takes precedence and NodeTypeID is only computed.
+			if js.NewCluster != nil && js.NewCluster.InstancePoolID != "" {
+				js.NewCluster.NodeTypeID = ""
+			}
+			// Same for Driver.
+			if js.NewCluster != nil && js.NewCluster.DriverInstancePoolID != "" {
+				js.NewCluster.DriverNodeTypeID = ""
+			}
```
Comment (alexott) [inline jobs/resource_job.go:834]: it makes sense to make it not only for new clusters, but also for job clusters.  We really have following clusters in job resource:

1. new cluster on resource level (compatibility with single task API 2.0)
2. new cluster on task level
3. job clusters

We need to support all of them.  Also it makes sense to fix it for `databricks_cluster` as well. We also have #2141

**Review by alexott — CHANGES_REQUESTED** [review]

File: jobs/resource_job_test.go [hunk 2]
```diff
@@ -1419,6 +1419,113 @@ func TestResourceJobUpdate(t *testing.T) {
...
+		ID:       "789",
+		Update:   true,
+		Resource: ResourceJob(),
+		InstanceState: map[string]string{
+			"new_cluster.0.node_type_id":                      "node-type-id",
+			"new_cluster.0.driver_node_type_id":               "driver-node-type-id",
+			"task.0.new_cluster.0.node_type_id":               "node-type-id-task",
+			"task.0.new_cluster.0.driver_node_type_id":        "driver-node-type-id-task",
+			"job_cluster.0.new_cluster.0.node_type_id":        "node-type-id-job",
+			"job_cluster.0.new_cluster.0.driver_node_type_id": "driver-node-type-id-job",
```
Comment (mgyucht) [inline jobs/resource_job_test.go:1493]: micronit: let's align the names you use so they are consistent between node types and instance pools, just makes it a bit easier to see what corresponds to what
```suggestion
			"new_cluster.0.node_type_id":                      "node-type-id-worker",
			"new_cluster.0.driver_node_type_id":               "node-type-id-driver",
			"task.0.new_cluster.0.node_type_id":               "node-type-id-worker-task",
			"task.0.new_cluster.0.driver_node_type_id":        "node-type-id-driver-task",
			"job_cluster.0.new_cluster.0.node_type_id":        "node-type-id-worker-job",
			"job_cluster.0.new_cluster.0.driver_node_type_id": "node-type-id-driver-job",
```

File: jobs/resource_job.go [hunk 3]
```diff
@@ -823,6 +823,21 @@ func ResourceJob() *schema.Resource {
 			if js.isMultiTask() {
 				ctx = context.WithValue(ctx, common.Api, common.API_2_1)
 			}
+
```
Comment (mgyucht) [inline jobs/resource_job.go:826]: So that this Update function does not get humongous, would you mind pulling this into a separate function like `prepareJobSettingsForUpdate`?

File: clusters/clusters_api.go [hunk 4]
```diff
@@ -444,6 +444,19 @@ func (cluster Cluster) Validate() error {
 	return fmt.Errorf("NumWorkers could be 0 only for SingleNode clusters. See https://docs.databricks.com/clusters/single-node.html for more details")
 }
 
+// ResolveComputedAttributesForAPIRequest prepocesses the cluster configuration to remove conflicting computed attributes before we can make an API request.
+func (cluster *Cluster) ResolveComputedAttributesForAPIRequest() {
```
Comment (mgyucht) [inline clusters/clusters_api.go:448]: Does this need to be public?
```suggestion
func (cluster *Cluster) resolveComputedAttributesForAPIRequest() {
```

**Review by mgyucht — APPROVED** [review]
LGTM provided we address these three nits.

File: jobs/resource_job_test.go (hunk 2 above)
Comment (marekbrysa) [reply jobs/resource_job_test.go:1493]: Hmm, I followed the pattern of how the attributes are named...

File: clusters/clusters_api.go (hunk 4 above)
Comment (marekbrysa) [reply clusters/clusters_api.go:448]: I think so, because this is in the `clusters` package, and I'm using it in `jobs`?

File: jobs/resource_job_test.go (hunk 2 above)
Comment (mgyucht) [reply jobs/resource_job_test.go:1493]: It's fine, it is just slightly inconsistent with the instance pools literals you used. Or, vice-versa, you could rename the parameters "instance-pool-job" and "driver-instance-pool-job" in the request & HCL.

File: clusters/clusters_api.go (hunk 4 above)
Comment (mgyucht) [reply clusters/clusters_api.go:448]: You're absolutely correct, my mistake.

File: jobs/resource_job.go (hunk 3 above)
Comment (marekbrysa) [reply jobs/resource_job.go:842]: Done.

**Review by mgyucht — APPROVED** [review]
LGTM!

**Comment by marekbrysa** [comment]
@mgyucht I found that there's an existing function that does what I wanted and more: https://github.com/databricks/terraform-provider-databricks/blob/650a34fce9da81d3962f932fb555128954501df3/clusters/clusters_api.go#L448

**Comment by marekbrysa** [comment]
Somehow I'm now getting panics (nil dereference) when I try to apply... Will investigate further.

**Comment by mgyucht** [comment]
Discussed offline: this was manually tested in AWS and Azure.

**Review by alexott — APPROVED** [review]
