### PR TITLE
Fix `force_destroy` behaviour for `databricks_schema`

### LINKED ISSUE #2906: [ISSUE] `databricks_schema` resource force_destroy does not handle function or volume
### Configuration
```hcl
resource "databricks_schema" "things" {
  catalog_name = databricks_catalog.sandbox.id
  name         = "things"
  force_destroy = true
}
```

### Expected Behavior
Documentation states:

[force_destroy](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/schema#force_destroy) - (Optional) Delete schema regardless of its contents.

Expects schema and all content to be dropped. 

### Actual Behavior
All tables and views are dropped. But Volumes and Functions are not.
Terraform destroy operation throws error:
│ Error: cannot delete schema: Schema 'sandbox.things' is not empty. The schema has 0 tables(s), 1 functions(s), 1 volumes(s)

### Steps to Reproduce
1. Create schema in Unity Catalog using terraform
2. Create table(s), view(s), function(s) and volume(s) in schema outside of Terraform
3. Run terraform destroy

### Terraform and provider versions
databricks/databricks 1.29

### PR DESCRIPTION
**Pull request by nkvuong**
## Changes
Also delete volumes, functions & models when force destroy a schema

Closes #2906

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [x] covered with integration tests in `internal/acceptance`
- [x] relevant acceptance tests are passing
- [x] using Go SDK

### CODE REVIEW

**Review by alexott — APPROVED** [review]

File: catalog/resource_schema.go [hunk 1]
```diff
@@ -107,6 +108,39 @@ func ResourceSchema() *schema.Resource {
...
+					CatalogName: strings.Split(name, ".")[0],
+					SchemaName:  strings.Split(name, ".")[1],
+				})
+				if err != nil {
+					return err
+				}
+				for _, v := range volumes {
+					w.Volumes.DeleteByFullNameArg(ctx, v.FullName)
+				}
+				// delete all volumes
```
Comment (troyel) [inline catalog/resource_schema.go:122]:
```suggestion
				// delete all functions
```

**Comment by nkvuong** [comment]
acceptance tests passed
