### PR TITLE
Fix `ADMIN` assignment in `databricks_permission_assignment` resource

### LINKED ISSUE #5106: [ISSUE] Issue with `databricks_permission_assignment` resource
### Configuration

```hcl
# Create a local module with following resource block
resource "databricks_permission_assignment" "this" {
  group_name = var.group_name
  permissions  = ["ADMIN"]
}

# Calling the module in the TF workspace
module "assignment" {
  source = "./modules/permission-assignment"

  providers = {
    databricks = databricks.workspace
  } 

  group_name = "dan-guo-grp"
}

# databricks provider
provider "databricks" {
  alias = "workspace"
  host                        = "https://adb-2432776786089467.7.azuredatabricks.net"
  azure_workspace_resource_id = "xxxxxxxxxx"
  azure_client_id             = data.vault_generic_secret.azurerm_auth.data["xxxx"]
  azure_client_secret         = data.vault_generic_secret.azurerm_auth.data["xxxx"]
  azure_tenant_id             = data.vault_generic_secret.azurerm_auth.data["xxxx"]
}
```

### Expected Behavior
Terraform apply should be successful

### Actual Behavior
It's giving me the following error:

module.assignment.databricks_permission_assignment.this: Creating...
╷
│ Error: cannot create permission assignment: Invalid permission: ADMIN is invalid or not supported for this workspace.
│ 
│   with module.assignment.databricks_permission_assignment.this,
│   on modules/permission-assignment/main.tf line 1, in resource "databricks_permission_assignment" "this":
│    1: resource "databricks_permission_assignment" "this" {

### Steps to Reproduce

terraform apply

### Terraform and provider versions

1.92.0 or 1.93.0

### Is it a regression?

This is a new feature released in 1.92.0

### PR DESCRIPTION
**Pull request by alexott**
## Changes

It was found that assignment by name works only for the `USER` role, so the direct assignment as `ADMIN` fails.  This PR fixes this issue by doing assignment as `USER` first, and then changing it to `ADMIN`.

Resolves #5106

## Tests

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] using Go SDK
- [ ] using TF Plugin Framework
- [x] has entry in `NEXT_CHANGELOG.md` file

### CODE REVIEW

File: access/resource_permission_assignment.go [hunk 1]
```diff
@@ -148,11 +150,26 @@ func ResourcePermissionAssignment() common.Resource {
 			var assignment permissionAssignmentEntity
 			common.DataToStructPointer(d, s, &assignment)
 			api := NewPermissionAssignmentAPI(ctx, c)
+			shouldReassignAdmin := false
+			if assignment.PrincipalId == 0 && slices.Contains(assignment.Permissions, "ADMIN") {
+				shouldReassignAdmin = true
+				assignment.Permissions = []string{"USER"}
+			}
```
Comment (tanmay-db) [inline access/resource_permission_assignment.go:159]: Would be good to add why we are doing this in comments.

File: access/resource_permission_assignment_test.go [hunk 2]
```diff
@@ -101,6 +101,128 @@ func TestPermissionAssignmentCreateWithUserName(t *testing.T) {
 	}.ApplyNoError(t)
 }
 
+func TestPermissionAssignmentCreateWithUserNameAndAdminPermissions(t *testing.T) {
```
Comment (tanmay-db) [inline access/resource_permission_assignment_test.go:104]: Would be good to also have integration test for this

File: access/resource_permission_assignment.go (hunk 1 above)
Comment (alexott) [reply access/resource_permission_assignment.go:159]: Added

File: access/resource_permission_assignment_test.go (hunk 2 above)
Comment (alexott) [reply access/resource_permission_assignment_test.go:104]: Do we support integration tests with two providers? Because we need an account-level provider to create a group, and then a workspace-level provider to perform the assignment...
