### PR TITLE
Fix `databricks_mws_private_access_settings` creation

### LINKED ISSUE #3409: [ISSUE] Issue with `databricks_mws_private_access_settings` resource
### Configuration
```
resource "databricks_mws_private_access_settings" "pas" {
  private_access_settings_name = "${local.workspace_name} Private Access Settings"
  region                       = var.region
  public_access_enabled        = true
  private_access_level         = "ACCOUNT" 
} 
```

### Expected Behavior
The resource should get created

### Actual Behavior
An error stating account_id is required.
Except when I add account_id it tells me the argument is deprecated and I should not use it.  It works fine without account_id *once the resource already exists* but will not create the resource without account_id specified.

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
TF 1.7.2
Provider 1.38.0

### Is it a regression?
It worked fine in 1.31 and earlier *with* account_id without getting a deprecation warning

### PR DESCRIPTION
**Pull request by nkvuong**
## Changes
- `account_id` was not set correctly during creation, leading to failure during read
Closes #3409

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [x] using Go SDK

### CODE REVIEW

File: mws/resource_mws_private_access_settings.go [hunk 1]
```diff
@@ -12,36 +12,37 @@ import (
...
+		common.CustomizeSchemaPath(m, "private_access_settings_name").SetRequired()
+		common.CustomizeSchemaPath(m, "region").SetRequired()
 
-		s["private_access_level"].ValidateFunc = validation.StringInSlice([]string{"ACCOUNT", "ENDPOINT"}, true)
-		common.SetDefault(s["private_access_level"], "ACCOUNT")
+		common.CustomizeSchemaPath(m, "private_access_level").SetValidateFunc(validation.StringInSlice([]string{"ACCOUNT", "ENDPOINT"}, true))
+		common.CustomizeSchemaPath(m, "private_access_settings_id").SetComputed()
 
-		s["private_access_settings_id"].Computed = true
+		common.CustomizeSchemaPath(m, "private_access_level").SetValidateFunc(validation.StringInSlice([]string{"ACCOUNT", "ENDPOINT"}, true))
```
Comment (alexott) [inline mws/resource_mws_private_access_settings.go:23]: is it duplicate of line 20?

**Review by alexott — APPROVED** [review]
small comment

**Review by tanmay-db — APPROVED** [review]
