### PR TITLE
Exporter: improve exporting of `databricks_cluster_policy` resource

### LINKED ISSUE #2664: Custom cluster policy not getting exported using tf databricks exporter
### Configuration
terraform {
required_providers {
databricks = {
source = "databricks/databricks"
version = "1.21.0"
}
}
}

### Expected Behavior
Custom cluster policy should get exported using tf databricks exporter

### Actual Behavior
Custom cluster policy not getting exported using tf databricks exporter

### Steps to Reproduce

1. Create a new custom cluster policy using primary workspace >> Compute >> Policies >> Create Policy
2. Use terraform databricks exporter to export this policy 
3. We will see that only built in policies gets exported and we don't see the custom polices being exported

### Terraform and provider versions
$ terraform version
Terraform v1.1.7
on windows_amd64

provider registry.terraform.io/databricks/databricks v1.21.0

### PR DESCRIPTION
**Pull request by alexott**
## Changes

This includes:

- Listing of all cluster policies, not only that are referenced in the jobs/clusters.
- Emit secret scopes when they are referenced in Spark Conf or environment variables

Also, fixes generation of non-existent secret scopes that happens when we emit non-existent secret scope (for example, it's a dangling reference in cluster policy or old job configuration).

This fixes #2664

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] relevant acceptance tests are passing
- [x] using Go SDK

### CODE REVIEW

File: exporter/importables.go [hunk 1]
```diff
@@ -534,10 +535,38 @@ var resourcesMap map[string]importable = map[string]importable{
...
+		Service: "policies",
 		Name: func(ic *importContext, d *schema.ResourceData) string {
 			return d.Get("name").(string)
 		},
+		List: func(ic *importContext) error {
+			w, err := ic.Client.WorkspaceClient()
+			if err != nil {
+				return err
+			}
+			policies, err := w.ClusterPolicies.ListAll(ic.Context, compute.ListClusterPoliciesRequest{})
```
Comment (tanmay-db) [inline exporter/importables.go:547]: Why was listing all policies not required before?

File: exporter/importables.go [hunk 2]
```diff
@@ -534,10 +535,38 @@ var resourcesMap map[string]importable = map[string]importable{
...
+				}
+				if !ic.MatchesName(policy.Name) {
+					log.Printf("[INFO] Policy %s doesn't match %s filter", policy.Name, ic.match)
+					continue
+				}
+				ic.Emit(&resource{
+					Resource: "databricks_cluster_policy",
+					ID:       policy.PolicyId,
+				})
+				if offset%10 == 0 {
```
Comment (tanmay-db) [inline exporter/importables.go:564]: Is this for better readability on console?

File: exporter/importables.go [hunk 3]
```diff
@@ -556,7 +585,8 @@ var resourcesMap map[string]importable = map[string]importable{
 				defaultValue, dok := policy["defaultValue"]
 				typ := policy["type"]
 				if !vok && !dok {
-					log.Printf("[INFO] Skipping policy element as it doesn't have both value and defaultValue")
+					log.Printf("[DEBUG] Skipping policy element as it doesn't have both value and defaultValue. k='%v', policy='%v'",
```
Comment (tanmay-db) [inline exporter/importables.go:588]: If the above line is at INFO

> log.Printf("[INFO] Policy %s doesn't match %s filter", policy.Name, ic.match)

Then I think this should also be INFO?

File: exporter/importables.go [hunk 4]
```diff
@@ -582,6 +612,15 @@ var resourcesMap map[string]importable = map[string]importable{
 						ID:       eitherString(value, defaultValue),
 					})
 				}
+				if typ == "fixed" && (strings.HasPrefix(k, "spark_conf.") || strings.HasPrefix(k, "spark_env_vars.")) {
```
Comment (tanmay-db) [inline exporter/importables.go:615]: For my understanding can you explain this a bit more, why `fixed` is required?

File: exporter/importables.go (hunk 2 above)
Comment (alexott) [reply exporter/importables.go:564]: yeah, it should be DEBUG

File: exporter/importables.go (hunk 4 above)
Comment (alexott) [reply exporter/importables.go:615]: Because there are other types, like, `regexp` - in this case we won't be able to handle it

File: exporter/importables.go (hunk 1 above)
Comment (alexott) [reply exporter/importables.go:547]: It was an initial design decision from the beginning of development, but now customers are starting to ask for it. The new implementation can behave the old way - just don't provide `policies` in the `-listing` switch

File: exporter/importables.go (hunk 3 above)
Comment (alexott) [reply exporter/importables.go:588]: It will make things too noisy...

File: exporter/importables.go (hunk 2 above)
Comment (alexott) [reply exporter/importables.go:564]: fixed

**Review by tanmay-db — APPROVED** [review]
