### PR TITLE
Fix retrieving of latest DBR versions in `databricks_spark_version`

### LINKED ISSUE #5218: [ISSUE] Issue with `databricks_spark_version` resource not returning the latest_lts
### Configuration

Example one:

```hcl
terraform {
  required_providers {
    databricks = {
      source = "databricks/databricks"
    }
  }
}

data "databricks_spark_version" "latest_lts" {
  latest            = true
  long_term_support = true
  ml                = false
  genomics          = false
  gpu               = false
}

data "databricks_cluster_policy" "this" {
  count = var.policy_name != null ? 1 : 0
  name  = var.policy_name
}

resource "databricks_cluster" "this" {
  cluster_name            = var.name
  policy_id               = var.policy_name != null ? data.databricks_cluster_policy.this[0].id : null
  data_security_mode      = var.data_security_mode
  driver_node_type_id     = var.driver_node_type_id
  node_type_id            = var.node_type_id
  spark_version           = data.databricks_spark_version.latest_lts.id
  autotermination_minutes = var.autotermination_minutes
  is_pinned               = var.is_pinned
  runtime_engine          = var.runtime_engine
  custom_tags             = var.custom_tags
  num_workers             = var.num_workers != null ? var.num_workers : null
  dynamic "autoscale" {
    for_each = var.autoscale_min_workers != null && var.autoscale_max_workers != null ? [1] : []
    content {
      min_workers = var.autoscale_min_workers
      max_workers = var.autoscale_max_workers
    }
  }
}
```

Example two (manually setting the Scala version to 2.13):

```hcl
terraform {
  required_providers {
    databricks = {
      source = "databricks/databricks"
    }
  }
}

data "databricks_spark_version" "latest_lts" {
  latest            = true
  long_term_support = true
  ml                = false
  genomics          = false
  gpu               = false
  scala             = "2.13"
}

data "databricks_cluster_policy" "this" {
  count = var.policy_name != null ? 1 : 0
  name  = var.policy_name
}

resource "databricks_cluster" "this" {
  cluster_name            = var.name
  policy_id               = var.policy_name != null ? data.databricks_cluster_policy.this[0].id : null
  data_security_mode      = var.data_security_mode
  driver_node_type_id     = var.driver_node_type_id
  node_type_id            = var.node_type_id
  spark_version           = data.databricks_spark_version.latest_lts.id
  autotermination_minutes = var.autotermination_minutes
  is_pinned               = var.is_pinned
  runtime_engine          = var.runtime_engine
  custom_tags             = var.custom_tags
  num_workers             = var.num_workers != null ? var.num_workers : null
  dynamic "autoscale" {
    for_each = var.autoscale_min_workers != null && var.autoscale_max_workers != null ? [1] : []
    content {
      min_workers = var.autoscale_min_workers
      max_workers = var.autoscale_max_workers
    }
  }
}
```

### Expected Behavior
"databricks_spark_version" "latest_lts" should by default return the latest LTS independent of the Scala version, or there should be an option to filter for a specific Scala version when required.
latest_lts should be in sync with the Databricks cluster policy, and deployments should not fail when defining latest_lts in both.

### Actual Behavior
"databricks_spark_version" "latest_lts" by default is filtering for Scala 2.12, but the 17.x LTS has only support for Scala 2.13; it returns 16.4 as the latest LTS.

When defining the filter for Scala 2.13 manually, it fails the policy check as the Databricks policy also does not return the correct LTS.

### Steps to Reproduce

1. terraform plan -> No error since policy is only checked in apply
2. terraform apply -> Error as shown above since auto:latest-lts does not include 17.3 LTS

### Terraform and provider versions
1.97

### Is it a regression?
N/A

### Debug Output
```hcl
module.cluster_compute["Shared Central Cluster"].databricks_cluster.this: Modifying... [id=0630-140135-jjrzdty3]
╷
│ Error: cannot update cluster: Validation failed for spark_version, needs to be one of (17.2.x-scala2.13, 16.4.x-scala2.12, 17.2.x-cpu-ml-scala2.13, 16.4.x-cpu-ml-scala2.12, 16.4.x-scala2.12, 15.4.x-scala2.12, 16.4.x-cpu-ml-scala2.12, 15.4.x-cpu-ml-scala2.12) (is an element in "List(17.3.x-scala2.13)")
│ 
│   with module.cluster_compute["Shared Central Cluster"].databricks_cluster.this,
│   on ../modules/cluster_compute/main.tf line 38, in resource "databricks_cluster" "this":
│   38: resource "databricks_cluster" "this" {
│ 
```
### Important Factoids
N/A

### Would you like to implement a fix?
No

### PR DESCRIPTION
**Pull request by alexott**
## Changes

This is a second part of fixing issue #5218. The `databricks_spark_version` is now correctly handles DBRs with Scala 2.13 and able to retrieve DBR 17.3 as latest LTS.

Resolves #5218

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] using Go SDK
- [ ] using TF Plugin Framework
- [x] has entry in `NEXT_CHANGELOG.md` file

### CODE REVIEW

File: clusters/data_spark_version_test.go [hunk 1]
```diff
@@ -19,7 +19,7 @@ func TestSparkVersionLatest(t *testing.T) {
 			e := m.GetMockClustersAPI().EXPECT()
 			e.SelectSparkVersion(mock.Anything, compute.SparkVersionRequest{
 				Latest: true,
-				Scala:  "2.12",
+				Scala:  "2.1",
```
Comment (tanmay-db) [inline clusters/data_spark_version_test.go:22]: I think it would be good to add integration test for this

**Review by tanmay-db — APPROVED** [review]

File: clusters/data_spark_version_test.go (hunk 1 above)
Comment (alexott) [reply clusters/data_spark_version_test.go:22]: We have tests for that data source via its use in jobs/clusters/mounts tests.

Comment (alexott) [reply clusters/data_spark_version_test.go:22]: Added a separate test.

**Comment by pcsrijith** [comment]
@alexott : I believe after 1.99.0, we are still seeing DBR 16.4, instead of 17.3

**Comment by alexott** [comment]
It's not released yet. Most probably - Monday.

**Comment by pcsrijith** [comment]
@alexott something wrong with 1.100 version? I see it was released, however, [provider](https://registry.terraform.io/providers/databricks/databricks/latest/docs) link still points to 1.99.0 as latest version
