### PR TITLE
Fix node_type data source by skipping node types that aren't available from cloud provider

### LINKED ISSUE #1533: [ISSUE] Issue with data `databricks_node_type` (Azure) while setting local_disk = true
When we set local_disk=true in data “databricks_node_type” to fetch the node, it picks up unsupported node(Standard_L8as_v3) in the region (Central India) as well. 

While the [list-node-types](https://docs.databricks.com/dev-tools/api/latest/clusters.html#list-node-types) API is called in the process and receives the below status for that unsupported node in the response **(for Azure)**- 

"node_info": {
        "status": [
          "NotEnabledOnSubscription",
          "NotAvailableInRegion"
        ]
}

The data “databricks_node_type” doesn’t honor the "NotAvailableInRegion" status for that node_type_id and give that as a response. 

_Went through the [provider code](https://github.com/databricks/terraform-provider-databricks/blob/master/clusters/data_node_type.go) and doesn’t look like the exception is handled._

### Configuration
```hcl
data "databricks_node_type" "smallest" {
  local_disk = true
}

data "databricks_spark_version" "latest_lts" {
  long_term_support = true
}

resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = "Shared Autoscaling"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20
  autoscale {
    min_workers = 1
    max_workers = 50
  }
}
```

### Expected Behavior
The node_type_id returned via data "databricks_node_type" should be a supported one in that region. (Azure)

### Actual Behavior
It is returning unsupported nodes too, for e.g Standard_L8as_v3 in Central India (Azure)

Error thrown is - 
Could not launch cluster due to cloud provider failures. azure_error_code: InvalidParameter, azure_error_message: The requested VM size Standard_L8as_v3 is not available in the current region. The ..., Termination info: code: CLOUD_PROVIDER_LAUNCH_FAILURE, type: CLOUD_FAILURE, parameters: map[azure_error_code:InvalidParameter azure_error_message:The requested VM size Standard_L8as_v3 is not available in the current region. 

### Steps to Reproduce
You can run the above code in a workspace region where the Standard_L8as_v3 node is not supported.

### Debug Output
https://gist.github.com/pratik-databricks/d92103543eeb7f21b6ef6358233687cb

### PR DESCRIPTION
**Pull request by alexott**
Also, fixed tests that use azure-cli - Go stopped to execute programs when PATH has relative paths

This fixes #1533

### CODE REVIEW

File: clusters/data_node_type.go [hunk 1]
```diff
@@ -117,6 +122,18 @@ func (a ClustersAPI) GetSmallestNodeType(r NodeTypeRequest) string {
 	}
 	list.Sort()
 	for _, nt := range list.NodeTypes {
+		if nt.NodeInfo != nil {
+			shouldBeSkipped := false
+			for _, st := range nt.NodeInfo.Status {
+				if st == CloudProviderNodeStatusNotAvailableInRegion || st == CloudProviderNodeStatusNotEnabled {
+					shouldBeSkipped = true
```
Comment (nfx) [inline clusters/data_node_type.go:129]: please create a method on NodeInfo and reduce the level of nesting to one

**Review by nfx — CHANGES_REQUESTED** [review]

File: clusters/data_node_type.go [hunk 2]
```diff
@@ -89,6 +94,19 @@ type NodeType struct {
...
+func (nt NodeType) shouldBeSkipped() bool {
+	shouldBeSkipped := false
+	if nt.NodeInfo != nil {
+		for _, st := range nt.NodeInfo.Status {
+			if st == CloudProviderNodeStatusNotAvailableInRegion || st == CloudProviderNodeStatusNotEnabled {
+				shouldBeSkipped = true
+				break
+			}
+		}
+	}
```
Comment (redcape) [inline clusters/data_node_type.go:106]: should we also check `node_info.available_core_quota >= num_cores`

Comment (alexott) [reply clusters/data_node_type.go:106]: not sure if it will help a lot, as we're working on the individual node level...

Comment (redcape) [reply clusters/data_node_type.go:106]: I suppose it depends on the use-case. For mounts, it will help since we only start one node always and use it for all mounts. When the use-case is to for user-defined clusters, it's less clear how much it would help since the number of cluster and number of executors is unknown at this stage.

File: clusters/data_node_type.go [hunk 3]
```diff
@@ -89,6 +94,19 @@ type NodeType struct {
 	Graviton              bool                          `json:"is_graviton,omitempty"`
 }
 
+func (nt NodeType) shouldBeSkipped() bool {
+	shouldBeSkipped := false
+	if nt.NodeInfo != nil {
```
Comment (nfx) [inline clusters/data_node_type.go:99]: i'll quote my favorite chapter from https://livebook.manning.com/book/100-go-mistakes-how-to-avoid-them/chapter-2/v-10/30
image

File: clusters/data_node_type.go [hunk 4]
```diff
@@ -89,6 +94,19 @@ type NodeType struct {
...
+		for _, st := range nt.NodeInfo.Status {
+			if st == CloudProviderNodeStatusNotAvailableInRegion || st == CloudProviderNodeStatusNotEnabled {
```
Comment (nfx) [inline clusters/data_node_type.go:101]: nit: i think switch statement would look more elegant here

File: clusters/data_node_type.go [hunk 5]
```diff
@@ -89,6 +94,19 @@ type NodeType struct {
...
+				shouldBeSkipped = true
```
Comment (nfx) [inline clusters/data_node_type.go:102]: why not immediately return here? would be more robust.

**Review by nfx — CHANGES_REQUESTED** [review]

File: clusters/data_node_type.go (hunk 5 above)
Comment (alexott) [reply clusters/data_node_type.go]: addressed all comments

File: clusters/data_node_type.go [hunk 6]
```diff
@@ -89,6 +94,18 @@ type NodeType struct {
 	Graviton              bool                          `json:"is_graviton,omitempty"`
 }
 
+func (nt NodeType) shouldBeSkipped() bool {
+	if nt.NodeInfo != nil {
```
Comment (nfx) [inline clusters/data_node_type.go:98]: can we further simplify it to `if nt.NodeInfo == nil return false`?

**Review by nfx — CHANGES_REQUESTED** [review]

File: clusters/data_node_type.go (hunk 2 above)
Comment (redcape) [reply clusters/data_node_type.go]: comment doesn't block merge

**Review by nfx — APPROVED** [review]
