### PR TITLE
[Fix] Fix filling of missing attributes in `databricks_quality_monitor`

### LINKED ISSUE #4518: [ISSUE] Issue with `databricks_quality_monitor` resource
### Configuration

```hcl
data "databricks_table" "cleaned_events_table" {
  name = "my_catalog.my_schema.cleaned_events"
}

resource "databricks_sql_endpoint" "monitoring_serverless" {
  name = "my-serverless-warehouse-for-monitoring"

  cluster_size   = "2X-Small"
  auto_stop_mins = 1

  enable_serverless_compute = true
}

resource "databricks_quality_monitor" "cleaned_events_timeseries_monitor" {
  table_name         = data.databricks_table.cleaned_events_table.name
  assets_dir         = join(
    "/",
    [
      data.databricks_current_user.terraform_user.home,
      "some",
      "path",
      "to",
      "files",
    ]
  )
  warehouse_id       = databricks_sql_endpoint.monitoring_serverless.id
  output_schema_name =  "my_catalog.my_schema"
  time_series {
    granularities = ["1 day"]
    timestamp_col = "my_timestamp_col"
  }

  schedule {
    quartz_cron_expression = "0 0 4 * * ?"
    timezone_id = "UTC"
  }
}
```

### Expected Behavior

Deploy should succeed.

### Actual Behavior

Error when deploying quality monitor:
```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to databricks_quality_monitor.cleaned_events_timeseries_monitor, provider "provider[\"registry.terraform.io/databricks/databricks\"]"
│ produced an unexpected new value: .warehouse_id: was cty.StringVal("109a725fd8187d7e"), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
```
- databricks/databricks v1.66.0
```

### Is it a regression?

Unsure.

### Debug Output

N/A. Environment is locked down.

### Important Factoids

N/A.

### Would you like to implement a fix?

Not sure where the problem lies, but happy to help if directed.

### PR DESCRIPTION
**Pull request by alexott**
## Changes

The quality monitor Get API doesn't return attributes `warehouse_id` and `skip_builtin_dashboard` set by the Create API, leading to configuration drift and errors. We can backfill them from the existing state.

Resolves #4518

## Tests

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [ ] using Go SDK
- [ ] using TF Plugin Framework

### CODE REVIEW

File: catalog/online_table_test.go [hunk 1]
```diff
@@ -27,26 +27,13 @@ resource "databricks_catalog" "sandbox" {
...
-  
-  resource "databricks_sql_table" "table" {
+    resource "databricks_sql_table" "table" {
 	catalog_name       = databricks_catalog.sandbox.id
 	schema_name        = databricks_schema.things.name
 	name               = "ot_src_{var.STICKY_RANDOM}"
 	table_type         = "MANAGED"
 	data_source_format = "DELTA"
-	warehouse_id       = databricks_sql_endpoint.this.id
+	warehouse_id       = "{env.TEST_DEFAULT_WAREHOUSE_ID}"
```
Comment (nkvuong) [inline catalog/online_table_test.go:36]: I assume these changes should go to a separate PR?

**Review by nkvuong — APPROVED** [review]
lgtm

File: catalog/resource_quality_monitor.go [hunk 2]
```diff
@@ -90,7 +90,18 @@ func ResourceQualityMonitor() common.Resource {
 				return err
 
 			}
-			return common.StructToData(endpoint, monitorSchema, d)
+			oldWarehouseId := d.Get("warehouse_id").(string)
+			oldSkipBuiltinDashboard := d.Get("skip_builtin_dashboard").(bool)
```
Comment (nkvuong) [inline catalog/resource_quality_monitor.go:94]: these fields only available for create, not update - should we flag this in the doc as well?

File: catalog/online_table_test.go (hunk 1 above)
Comment (alexott) [reply catalog/online_table_test.go:36]: Yeah, they can - I wanted to speedup tests. I'll wait until this test passes, and then carve these changes out of this PR

File: catalog/resource_quality_monitor.go (hunk 2 above)
Comment (alexott) [reply catalog/resource_quality_monitor.go:94]: yes, good idea.
