### PR TITLE
[Fix] Handle deleted cluster gracefully

### LINKED ISSUE #4277: [ISSUE] Issue with `databricks_library` resource when cluster is deleted
### Configuration

```hcl
data "databricks_node_type" "smallest" {
  local_disk = true
}

data "databricks_spark_version" "latest_lts" {
  long_term_support = true
}

resource "databricks_cluster" "this" {
  cluster_name            = "this-cluster"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 10
  autoscale {
    min_workers = 0
    max_workers = 2
  }
}

resource "databricks_library" "this" {
  cluster_id = databricks_cluster.this.cluster_id
  pypi {
    package = "databricks-sdk==0.8.0"
  }
}
```

### Expected Behavior
When a cluster is deleted outside of Terraform, the next run of `terraform plan` should recreate the cluster and the library.

### Actual Behavior

`terraform apply` fails with:
```
╷
│ Error: failed to wait for library installation
│ 
│ Cluster 1234-123456-1abcdefg does not exist
╵
╷
```

### Steps to Reproduce

1. Run `terraform apply`
2. Delete the cluster manually from the Databricks control plane
3. Run `terraform apply` again

### Terraform and provider versions

```
Terraform v1.10.0
+ provider registry.terraform.io/databricks/databricks v1.59.0
```
### Is it a regression?

This bug appears to have been reintroduced for the third time (!) - see previous issues #3679 and #1737.

I can confirm that this issue does not exist in [v1.52.0](https://github.com/databricks/terraform-provider-databricks/releases/tag/v1.52.0).

### PR DESCRIPTION
**Pull request by mgyucht**
## Changes
When migrating the `databricks_library` resource to the Plugin Framework, some logic that handled missing clusters was unintentionally reverted. This PR adds (back) explicit handling for deleted clusters in `databricks_library` resources.

Resolves #4277.
## Tests

Added an integration test that permanently deletes the cluster before running apply again. The cluster and library are then recreated.

### CODE REVIEW

File: internal/providers/pluginfw/products/library/resource_library.go [hunk 1]
```diff
@@ -35,28 +38,42 @@ func ResourceLibrary() resource.Resource {
...
+// If library cannot be found, either because the cluster doesn't exist, the library is not installed, or some other error, the first return value will be nil.
+// The returned diagnostics will contain any errors or warnings that occurred during the operation, and the caller should check for errors before continuing.
+func readLibrary(ctx context.Context, w *databricks.WorkspaceClient, waitParams compute.Wait, libraryRep string) (*LibraryExtended, diag.Diagnostics) {
+	var d diag.Diagnostics
 	res, err := libraries.WaitForLibrariesInstalledSdk(ctx, w, waitParams, libraryDefaultInstallationTimeout)
+	var apierr *apierr.APIError
+	if errors.As(err, &apierr) && clusterDoesNotExistRegex.MatchString(apierr.Message) {
+		d.AddWarning("cluster not found", fmt.Sprintf("cluster %s not found", waitParams.ClusterID))
+		return nil, d
+	}
```
Comment (alexott) [inline internal/providers/pluginfw/products/library/resource_library.go:53]: If the cluster doesn't exist. we need to mark this resource as not existing to force recreation - in SDK, it was done by setting the ID to an empty string. How it could be done in plugin framework?

Comment (mgyucht) [reply internal/providers/pluginfw/products/library/resource_library.go:53]: Great point. That still happens, but it uses State's RemoveResource method: https://github.com/databricks/terraform-provider-databricks/pull/4280/files#diff-8f0d49da80872819daa7eb548715a81ee693d7b05bc657cd160005d4995c0eacR202

**Review by alexott — APPROVED** [review]
