### PR TITLE
[Fix] enable updating `databricks_mws_ncc_private_endpoint_rule`

### LINKED ISSUE #4958: [FEATURE] Add Update API for Private Endpoint Rule

### PR DESCRIPTION
**Pull request by nkvuong**
## Changes
- Resolves #4958

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [x] covered with integration tests in `internal/acceptance`
- [x] using Go SDK
- [x] has entry in `NEXT_CHANGELOG.md` file

### CODE REVIEW

File: mws/resource_mws_ncc_private_endpoint_rule.go [hunk 1]
```diff
@@ -70,6 +73,52 @@ func ResourceMwsNccPrivateEndpointRule() common.Resource {
...
+			// only enabled, domain names & resource names are updatable
+			// they do require update_mask to be set
+			// resource_names are not applicable to Azure, so we exclude them from the update
+			updateMask := "enabled"
+			updatePrivateEndpointRule := settings.UpdatePrivateEndpointRule{
+				Enabled: d.Get("enabled").(bool),
+			}
+
+			if d.HasChange("domain_names") {
+				updateMask = "domain_names"
```
Comment (alexott) [inline mws/resource_mws_ncc_private_endpoint_rule.go]: it should be `updateMask = updateMask + ",domain_names"`, or just use a string array for names, and then do strings.Join before sending the request

File: mws/resource_mws_ncc_private_endpoint_rule.go [hunk 2]
```diff
@@ -70,6 +73,52 @@ func ResourceMwsNccPrivateEndpointRule() common.Resource {
...
+				newDomainNames := []string{}
+				for _, v := range d.Get("domain_names").([]any) {
+					newDomainNames = append(newDomainNames, v.(string))
+				}
+				updatePrivateEndpointRule.DomainNames = newDomainNames
+			} else if d.HasChange("resource_names") {
+				updateMask += "resource_names"
```
Comment (alexott) [inline mws/resource_mws_ncc_private_endpoint_rule.go]: comman is missing before `resource_names`

File: mws/resource_mws_ncc_private_endpoint_rule.go [hunk 3]
```diff
@@ -70,6 +73,52 @@ func ResourceMwsNccPrivateEndpointRule() common.Resource {
...
+			}
+
+			if d.HasChange("domain_names") {
+				updateMask = "domain_names"
+				newDomainNames := []string{}
+				for _, v := range d.Get("domain_names").([]any) {
+					newDomainNames = append(newDomainNames, v.(string))
+				}
+				updatePrivateEndpointRule.DomainNames = newDomainNames
+			} else if d.HasChange("resource_names") {
```
Comment (alexott) [inline mws/resource_mws_ncc_private_endpoint_rule.go]: I'm not sure if `else if` is needed here.  We can just use normal `if`.

File: mws/resource_mws_ncc_private_endpoint_rule.go [hunk 4]
```diff
@@ -70,6 +73,52 @@ func ResourceMwsNccPrivateEndpointRule() common.Resource {
...
+				NetworkConnectivityConfigId: nccId,
+				PrivateEndpointRuleId:       ruleId,
+				PrivateEndpointRule:         updatePrivateEndpointRule,
+				UpdateMask:                  updateMask,
+			})
+			if err != nil {
+				return err
+			}
+			common.StructToData(rule, s, d)
+			p.Pack(d)
```
Comment (alexott) [inline mws/resource_mws_ncc_private_endpoint_rule.go]: Do we need it here? We'll do `Read` after `Update` anyway

**Review by alexott — CHANGES_REQUESTED** [review]

**Review by alexott — APPROVED** [review]
