### PR TITLE
[Fix] Mark `default_catalog_name` attribute in `databricks_metastore_assignment` as deprecated

### LINKED ISSUE #4147: [ISSUE] Issue with `databrick_metastore_assignment` resource
### Configuration
```hcl
resource "databricks_metastore_assignment" "this" {
  metastore_id = databricks_metastore.this.id
  workspace_id = local.workspace_id
}
```
Note: No `default_catalog_name`

### Expected Behavior
No attempt should be made to manage the default catalog name

### Actual Behavior
default_catalog_name is defaulted to `hive_metastore`, the parameter is documented as deprecated. The default behavior should be to do nothing with the default_catalog_name.  

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
Terraform v1.9.8
on windows_amd64
+ provider registry.terraform.io/databricks v1.54.0
+ provider registry.terraform.io/azurerm v3.48.0

### Is it a regression?
No

### Would you like to implement a fix?
Please stop managing the default_catalog_name from databricks_metastore_assignment now that default_namespace_setting is the preferred method via the documentation.

### PR DESCRIPTION
**Pull request by nkvuong**
## Changes
- Mark `default_catalog_name` attribute in `databricks_metastore_assignment` as deprecated, as `databricks_default_namespace_setting` should be used instead. 
- Resolves #4147 

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [x] covered with integration tests in `internal/acceptance`

### CODE REVIEW

File: catalog/resource_metastore_assignment.go [hunk 1]
```diff
@@ -76,7 +77,6 @@ func ResourceMetastoreAssignment() common.Resource {
 					return err
 				}
 				d.Set("metastore_id", ma.MetastoreId)
-				d.Set("default_catalog_name", ma.DefaultCatalogName)
```
Comment (alexott) [inline catalog/resource_metastore_assignment.go:79]: if we marked it as `computed` we can still set it to the answer from backend?

Comment (nkvuong) [reply catalog/resource_metastore_assignment.go]: yes - I've added it back

**Review by alexott — APPROVED** [review]

**Review by tanmay-db — APPROVED** [review]
