### PR TITLE
[Fix] Use correct domain for Azure Gov and China

### LINKED ISSUE #4272: [ISSUE] Issue with `databricks_mount` resource on Azure Government
### Configuration

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>4.0"
    }
    databricks = {
      source  = "databricks/databricks"
      version = "~>1.0"
    }
  }
}

provider "azurerm" {
  features {}
  environment = "usgovernment"
}

provider "databricks" {
  # ...
}

data "azurerm_client_config" "current" {}

resource "azurerm_storage_account" "example" {
  # ...
}

resource "azurerm_storage_container" "example" {
  # ...
}

resource "databricks_secret_scope" "example" {
  # ...
}

resource "databricks_mount" "this" {
  name = "${azurerm_storage_account.example.name}/${azurerm_storage_container.example.name}/"
  uri  = "abfss://${azurerm_storage_container.example.name}@${azurerm_storage_account.example.name}.dfs.core.usgovcloudapi.net/"
  extra_configs = {
    "fs.azure.account.auth.type"                          = "OAuth",
    "fs.azure.account.oauth.provider.type"                = "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider",
    "fs.azure.account.oauth2.client.id"                   = "{{secrets/${databricks_secret_scope.example.id}/clientid}}",
    "fs.azure.account.oauth2.client.secret"               = "{{secrets/${databricks_secret_scope.example.id}/password}}",
    "fs.azure.account.oauth2.client.endpoint"             = "https://login.microsoftonline.com/${data.azurerm_client_config.current.tenant_id}/oauth2/token",
    "fs.azure.createRemoteFileSystemDuringInitialization" = "false",
  }
}
```

### Expected Behavior

The mount should be created as expected.

### Actual Behavior

When using the `abfs` block to create a mount in Azure Government, the mount fails with the following error: `Error: cannot create mount: Mount failed due to invalid mount source [abfss..//<container_name>@<sa_name>.dfs.core.windows.net]`.

This error is thrown because the URI is incorrect for storage accounts in Azure Government. Instead, the URI should end with `core.usgovcloudapi.net`. See [here](https://github.com/databricks/terraform-provider-databricks/blob/main/storage/adls_gen2_mount.go#L24) for the source of the problem.

### Steps to Reproduce

1. Create a storage account/container in Azure Government
2. Use the `abfs` block in a `databricks_mount` resource to mount the container to a Databricks workspace
3. Terraform apply

### Terraform and provider versions

```
Terraform v1.9.6
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.59.0
+ provider registry.terraform.io/hashicorp/azurerm v4.11.0
```

### Is it a regression?

No

### Important Factoids

- This should only be a problem on Azure Government, potentially other Azure Clouds that do not use the standard `dfs.core.windows.net` zone for storage accounts.

### Would you like to implement a fix?

Not immediately.

### Workaround
You can workaround this issue by using a combination of the `uri` and `extra_configs` parameters like the example below.
```hcl
resource "databricks_mount" "example" {
  name       = "${azurerm_storage_account.example.name}/${azurerm_storage_container.example.name}/"
  uri        = "abfss://${azurerm_storage_container.example.name}@${azurerm_storage_account.example.name}.dfs.core.usgovcloudapi.net/"
  extra_configs = {
    "fs.azure.account.auth.type"                          = "OAuth",
    "fs.azure.account.oauth.provider.type"                = "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider",
    "fs.azure.account.oauth2.client.id"                   = "{{secrets/${databricks_secret_scope.example.id}/clientid}}",
    "fs.azure.account.oauth2.client.secret"               = "{{secrets/${databricks_secret_scope.example.id}/clientsecret}}",
    "fs.azure.account.oauth2.client.endpoint"             = "https://login.microsoftonline.com/${data.azuread_client_config.current.tenant_id}/oauth2/token",
    "fs.azure.createRemoteFileSystemDuringInitialization" = "false",
  }
}
```
This will make the provider use the correct URI.

### PR DESCRIPTION
**Pull request by alexott**
## Changes

Resolves #4272

## Tests

- [x] `make test` run locally
- [ ] relevant change in `docs/` folder
- [ ] covered with integration tests in `internal/acceptance`
- [x] relevant acceptance tests are passing
- [ ] using Go SDK

### CODE REVIEW

File: storage/adls_gen2_mount.go [hunk 1]
```diff
@@ -19,10 +21,23 @@ type AzureADLSGen2Mount struct {
 	InitializeFileSystem bool   `json:"initialize_file_system"`
 }
 
+func getAzureDomain(client *common.DatabricksClient) string {
+	domains := map[string]string{
+		"PUBLIC":       "core.windows.net",
+		"USGOVERNMENT": "core.usgovcloudapi.net",
+		"CHINA":        "core.chinacloudapi.cn",
+	}
```
Comment (tanmay-db) [inline storage/adls_gen2_mount.go:29]: Is this list published somewhere?

**Review by tanmay-db — APPROVED** [review]

File: storage/adls_gen2_mount.go (hunk 1 above)
Comment (alexott) [reply storage/adls_gen2_mount.go:29]: yes - you can get it with azure-cli: https://github.com/databricks/terraform-provider-databricks/issues/4272#issuecomment-2504650693 and in the corresponding docs: https://learn.microsoft.com/en-us/azure/reliability/sovereign-cloud-china
