### PR TITLE
Fixed `databricks_entitlements` resource edge behaviour

### LINKED ISSUE #2382: [ISSUE] Creating `databricks_entitlements` fails if all entitlements are false
If you create a `databricks_entitlements` with all entitlements set to false (`allow_cluster_create`, `allow_instance_pool_create`, `databricks_sql_access`, `workspace_access`)
Terraform will fail with the following error:
```
╷
│ Error: cannot create entitlements: Error in performing the patch operation on group resource.
│ 
│   with databricks_entitlements.this,
│   on main.tf line 44, in resource "databricks_entitlements" "this":
│   44: resource "databricks_entitlements" "this" {
│ 
╵
```

### Configuration

A fully-functioning minimal example that reproduces the problem, with steps that describe how to reproduce can be found here:
https://github.com/scheleaap/databricks-issues/tree/false-entitlements

The most relevant code:

```hcl
resource "databricks_entitlements" "this" {
  provider = databricks.workspace
  depends_on = [databricks_mws_permission_assignment.this]

  group_id                   = databricks_group.this.id
  allow_cluster_create       = false
  allow_instance_pool_create = false
  databricks_sql_access      = false
  workspace_access           = false
}
```

### Expected Behavior

The entitlements are set to false, regardless of their previous value.

### Actual Behavior

The provider returns an error and the original entitlements values remain.

```
╷
│ Error: cannot create entitlements: Error in performing the patch operation on group resource.
│ 
│   with databricks_entitlements.this,
│   on main.tf line 44, in resource "databricks_entitlements" "this":
│   44: resource "databricks_entitlements" "this" {
│ 
╵
```

### Steps to Reproduce

A fully-functioning minimal example that reproduces the problem, with steps that describe how to reproduce can be found here:
https://github.com/scheleaap/databricks-issues/tree/false-entitlements

### Terraform and provider versions

```
Terraform v1.4.0
on linux_amd64
+ provider registry.terraform.io/databricks/databricks v1.18.0
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/time v0.9.1

Your version of Terraform is out of date! The latest version
is 1.4.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Debug Output

https://github.com/scheleaap/databricks-issues/blob/false-entitlements/tf-debug.log

### PR DESCRIPTION
**Pull request by nkvuong**
## Changes

Fix edge cases behaviour for `databricks_entitlements`
- [x] Resource creation failed when all entitlements set to `false`
- [x] Resource did not enforce entitlements that were removed out of bound
- [x] Cannot delete resource if identity has no entitlement: `Error: cannot delete entitlements: invalidPath No such attribute with the name : entitlements in the current resource`

Close #2382

## Tests

- [x] `make test` run locally
- [x] relevant change in `docs/` folder
- [x] covered with integration tests in `internal/acceptance`
- [x] relevant acceptance tests are passing
- [x] ~using Go SDK~

### CODE REVIEW

File: scim/resource_entitlement.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ func ResourceEntitlements() *schema.Resource {
 	addEntitlementsToSchema(&entitlementSchema)
 	return common.Resource{
 		Create: func(ctx context.Context, d *schema.ResourceData, c *common.DatabricksClient) error {
-			return patchEntitlements(ctx, d, c, "add")
+			return patchEntitlements(ctx, d, c, "replace")
```
Comment (alexott) [inline scim/resource_entitlement.go:31]: My concern here is that we initialize entitlements with `false`, and when we start to replace them instead of adding, then people may lose the access?

Comment (nkvuong) [reply scim/resource_entitlement.go:31]: this resource is meant to enforce entitlement of said identity - the update function will enforce the entitlements anyway, so this change is to make it consistent

**Review by nfx — APPROVED** [review]
